-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type override. The third value is an optional increment multiplier for consumables. (feel free to expand the table with any other values you might need (i.e. special initial values, etc.)!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
ITEM_MAPPING = {
	[77700001] = { { "Lacerator" } },
	[77700002] = { { "Concussion" } },
	[77700003] = { { "Acid" } },
	[77700004] = { { "Agents" } },
	[77700005] = { { "Bee" } },
	[77700006] = { { "Static" } },
	[77700007] = { { "Shock" } },
	[77700008] = { { "Sniper" } },
	[77700009] = { { "Scorcher" } },
	[77700010] = { { "Laser" } },
	[77700011] = { { "Suck" } },
	[77700012] = { { "Moo" } },
	[77700013] = { { "RYNO" } },
	-- Porgressive Weapons
	[77700350] = { { "Lacerator" } },
	[77700351] = { { "Concussion" } },
	[77700352] = { { "Acid" } },
	[77700353] = { { "Agents" } },
	[77700354] = { { "Bee" } },
	[77700355] = { { "Static" } },
	[77700356] = { { "Shock" } },
	[77700357] = { { "Sniper" } },
	[77700358] = { { "Scorcher" } },
	[77700359] = { { "Laser" } },
	[77700360] = { { "Suck" } },
	[77700361] = { { "Moo" } },
	[77700362] = { { "RYNO" } },
	-- Weapon Mods
	[77700700] = { { "LacMod1" } },
	[77700701] = { { "LacMod2" },{ "LacMod2" },{ "LacMod2" } },
	[77700702] = { { "ConMod1" } },
	[77700703] = { { "ConMod2" },{ "ConMod2" } },
	[77700704] = { { "ConMod3" },{ "ConMod3" },{ "ConMod3" } },
	[77700705] = { { "AcidMod1" } },
	[77700706] = { { "AcidMod2" },{ "AcidMod2" } },
	[77700707] = { { "AgentsMod1" } },
	[77700708] = { { "AgentsMod2" },{ "AgentsMod2" } },
	[77700709] = { { "BeeMod1" } },
	[77700710] = { { "BeeMod2" },{ "BeeMod2" } },
	[77700711] = { { "StaticMod1" } },
	[77700712] = { { "StaticMod2" },{ "StaticMod2" } },
	[77700713] = { { "ShockMod1" } },
	[77700714] = { { "ShockMod2" },{ "ShockMod2" } },
	[77700715] = { { "ShockMod3" },{ "ShockMod3" },{ "ShockMod3" } },
	[77700716] = { { "SniperMod1" } },
	[77700717] = { { "SniperMod2" },{ "SniperMod2" } },
	[77700718] = { { "ScorchMod1" } },
	[77700719] = { { "ScorchMod2" },{ "ScorchMod2" } },
	[77700720] = { { "LaserMod1" } },
	[77700721] = { { "LaserMod2" },{ "LaserMod2" } },
	[77700722] = { { "SuckMod1" } },
	-- Progressive Weapon Mods
	[77700380] = { { "LacMod1" },{ "LacMod2" } },
	[77700381] = { { "ConMod1" },{ "ConMod2" },{ "ConMod3" } },
	[77700382] = { { "AcidMod1" },{ "AcidMod2" } },
	[77700383] = { { "AgentsMod1" },{ "AgentsMod2" } },
	[77700384] = { { "BeeMod1" },{ "BeeMod2" } },
	[77700385] = { { "StaticMod1" },{ "StaticMod2" } },
	[77700386] = { { "ShockMod1" },{ "ShockMod2" },{ "ShockMod3" } },
	[77700387] = { { "SniperMod1" },{ "SniperMod2" } },
	[77700388] = { { "ScorchMod1" },{ "ScorchMod2" } },
	[77700389] = { { "LaserMod1" },{ "LaserMod2" } },
	[77700390] = { { "SuckMod1" } },
	-- Gadgets
	[77700101] = { { "Hypershot" } },
	[77700102] = { { "Sprout" } },
	[77700103] = { { "Polar" } },
	[77700104] = { { "PDA" } },
	[77700105] = { { "Shrink" } },
	[77700106] = { { "BoltGrab" } },
	[77700107] = { { "Map" } },
	[77700108] = { { "BoxBreak" } },
	[77700109] = { { "Heli" } },
	-- Planets
	[77700501] = { { "Pokitaru" } },
	[77700502] = { { "Kalidon" } },
	[77700503] = { { "Metalis" } },
	[77700504] = { { "Dreamtime" }, { "Station" }, { "Wreckage" } },
	[77700505] = { { "Challax" } },
	[77700506] = { { "Dayni Moon" }, { "Inside Clank" } },
	[77700507] = { { "Quodrona" } },
	[77700508] = { { "Ryllus" } },
	-- Armor
	[77700201] = { { "FireChest" } },
	[77700202] = { { "FireHelmet" },{ "FireHelmet" } },
	[77700203] = { { "FireGlove" },{ "FireGlove" },{ "FireGlove" } },
	[77700204] = { { "FireBoot" },{ "FireBoot" },{ "FireBoot" },{ "FireBoot" } },
	[77700205] = { { "SluChest" },{ "SluChest" },{ "SluChest" },{ "SluChest" },{ "SluChest" } },
	[77700206] = { { "SluHelmet" },{ "SluHelmet" },{ "SluHelmet" },{ "SluHelmet" },{ "SluHelmet" },{ "SluHelmet" } },
	[77700207] = { { "SluGlove" },{ "SluGlove" },{ "SluGlove" },{ "SluGlove" },{ "SluGlove" },{ "SluGlove" },{ "SluGlove" } },
	[77700208] = { { "SluBoot" },{ "SluBoot" },{ "SluBoot" },{ "SluBoot" },{ "SluBoot" },{ "SluBoot" },{ "SluBoot" },{ "SluBoot" } },
	[77700209] = { { "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" } },
	[77700210] = { { "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" } },
	[77700211] = { { "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" } },
	[77700212] = { { "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" } },
	[77700213] = { { "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" }, },
	[77700214] = { { "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" } },
	[77700215] = { { "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" } },
	[77700216] = { { "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" } },
	[77700217] = { { "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" } },
	[77700218] = { { "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" } },
	[77700219] = { { "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" } },
	[77700220] = { { "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" } },
	[77700221] = { { "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" } },
	[77700222] = { { "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" } },
	[77700223] = { { "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" } },
	[77700224] = { { "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" } },
	[77700225] = { { "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" }, },
	[77700226] = { { "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" } },
	[77700227] = { { "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" } },
	[77700228] = { { "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" } },
	-- Progressive Armor
	[77700370] = { { "FireChest" },{ "FireHelmet" },{ "FireGlove" },{ "FireBoot" } },
	[77700371] = { { "SluChest" },{ "SluChest" },{ "SluChest" },{ "SluChest" },{ "SluChest" },{ "SluHelmet" },{ "SluHelmet" },{ "SluHelmet" },{ "SluGlove" },{ "SluGlove" },{ "SluGlove" },{ "SluBoot" },{ "SluBoot" } },
	[77700372] = { { "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryChest" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryHelmet" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryGlove" },{ "CryBoot" },{ "CryBoot" },{ "CryBoot" } },
	[77700373] = { { "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleChest" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleHelmet" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleGlove" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" },{ "EleBoot" } },
	[77700374] = { { "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombChest" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombHelmet" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombGlove" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" },{ "BombBoot" } },
	[77700375] = { { "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypChest" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypHelmet" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypGlove" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" },{ "HypBoot" } },
	[77700376] = { { "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaChest" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaHelmet" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaGlove" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" },{ "ChaBoot" } },
	[77700377] = { { "FireChest" },{ "FireHelmet" },{ "FireGlove" },{ "FireBoot" },{ "SluChest" },{ "SluHelmet" },{ "SluGlove" },{ "SluBoot" },{ "CryChest" },{ "CryHelmet" },{ "CryGlove" },{ "CryBoot" },{ "EleChest" },{ "EleHelmet" },{ "EleGlove" },{ "EleBoot" },{ "BombChest" },{ "BombHelmet" },{ "BombGlove" },{ "BombBoot" },{ "HypChest" },{ "HypHelmet" },{ "HypGlove" },{ "HypBoot" },{ "ChaChest" },{ "ChaHelmet" },{ "ChaGlove" },{ "ChaBoot" } },
	[77700378] = { { "ProgNG" } }


	-- -- handle progressive_toggle as toggle, only changing it's active state
	-- [BASE_ITEM_ID + 00003] = { { "progressive_toggle", "toggle" } },
	-- -- multiple items on this id, add the consumable 3 times
	-- [BASE_ITEM_ID + 00004] = { { "toggle" }, { "consumable", nil, 3 } }
}
